//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaiLy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAODOANHSO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAOCAODOANHSO()
        {
            this.CTBAOCAODOANHSOes = new HashSet<CTBAOCAODOANHSO>();
        }
    
        public string MaBCDS { get; set; }
        public int Thang { get; set; }
        public long SoPhieuXuat { get; set; }
        public double TongTriGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTBAOCAODOANHSO> CTBAOCAODOANHSOes { get; set; }
    }
}
