//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaiLy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTBAOCAOCONGNODAILY
    {
        public string MaBaoCaoCongNo { get; set; }
        public string MaBaoCao { get; set; }
        public double NoDau { get; set; }
        public double NoCuoi { get; set; }
        public double PhatSinh { get; set; }
        public string MaCTPXH { get; set; }
    
        public virtual BAOCAOCONGNODAILY BAOCAOCONGNODAILY { get; set; }
        public virtual CTPHIEUXUATHANG CTPHIEUXUATHANG { get; set; }
    }
}
