//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaiLy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPHIEUXUATHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTPHIEUXUATHANG()
        {
            this.CTBAOCAOCONGNODAILies = new HashSet<CTBAOCAOCONGNODAILY>();
            this.CTPHIEUTHUTIENs = new HashSet<CTPHIEUTHUTIEN>();
        }
    
        public string MaCTPXH { get; set; }
        public string MaXuatHang { get; set; }
        public string MaHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTBAOCAOCONGNODAILY> CTBAOCAOCONGNODAILies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPHIEUTHUTIEN> CTPHIEUTHUTIENs { get; set; }
        public virtual MATHANG MATHANG { get; set; }
        public virtual PHIEUXUATHANG PHIEUXUATHANG { get; set; }
    }
}
