//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaiLy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAILY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DAILY()
        {
            this.PHIEUTHUTIENNOes = new HashSet<PHIEUTHUTIENNO>();
            this.PHIEUXUATHANGs = new HashSet<PHIEUXUATHANG>();
        }
    
        public string MaDaiLy { get; set; }
        public string TenDaiLy { get; set; }
        public int MaLoaiDaiLy { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public string Quan { get; set; }
        public System.DateTime NgayTiepNhan { get; set; }
    
        public virtual LOAIDAILY LOAIDAILY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUTHUTIENNO> PHIEUTHUTIENNOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUXUATHANG> PHIEUXUATHANGs { get; set; }
    }
}
