//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaiLy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUXUATHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUXUATHANG()
        {
            this.CTPHIEUXUATHANGs = new HashSet<CTPHIEUXUATHANG>();
        }
    
        public string MaXuatHang { get; set; }
        public string MaDaiLy { get; set; }
        public string MaHang { get; set; }
        public string TenMatHang { get; set; }
        public string DonViTinh { get; set; }
        public int SoLuong { get; set; }
        public double DonGia { get; set; }
        public double ThanhTien { get; set; }
        public System.DateTime NgayLapPhieu { get; set; }
        public double TongTien { get; set; }
        public double SoTienTra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPHIEUXUATHANG> CTPHIEUXUATHANGs { get; set; }
        public virtual DAILY DAILY { get; set; }
        public virtual MATHANG MATHANG { get; set; }
    }
}
