//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaiLy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHUTIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUTHUTIEN()
        {
            this.CTPHIEUTHUTIENs = new HashSet<CTPHIEUTHUTIEN>();
            this.PHIEUTHUTIENNOes = new HashSet<PHIEUTHUTIENNO>();
        }
    
        public string MaThuTien { get; set; }
        public double SoTienThu { get; set; }
        public System.DateTime NgayThuTien { get; set; }
        public double TienConLai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPHIEUTHUTIEN> CTPHIEUTHUTIENs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUTHUTIENNO> PHIEUTHUTIENNOes { get; set; }
    }
}
