//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaiLy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHUTIENNO
    {
        public string MaPhieu { get; set; }
        public string MaDaiLy { get; set; }
        public string MaThuTien { get; set; }
        public double SoTienThu { get; set; }
        public double TienConLai { get; set; }
    
        public virtual DAILY DAILY { get; set; }
        public virtual PHIEUTHUTIEN PHIEUTHUTIEN { get; set; }
    }
}
